(SELECT A.NAME 'results' FROM
(SELECT U.NAME, M.USER_ID, COUNT(M.USER_ID), DENSE_RANK() OVER (ORDER BY COUNT(M.USER_ID) DESC, U.NAME) AS 'RANK'
FROM USERS U
RIGHT JOIN MOVIERATING M
ON U.USER_ID = M.USER_ID
GROUP BY U.NAME) A
WHERE A.RANK = 1)
UNION ALL
(SELECT B.TITLE FROM
(SELECT MO.TITLE, AVG(M.RATING), DENSE_RANK() OVER (ORDER BY AVG(M.RATING) DESC, MO.TITLE) AS 'RATING'
FROM MOVIES MO
RIGHT JOIN MOVIERATING M
ON MO.MOVIE_ID = M.MOVIE_ID
WHERE DATE_FORMAT(CREATED_AT, '%Y-%m') = '2020-02'
GROUP BY M.MOVIE_ID) B
WHERE B.RATING = 1)